services:
  # Redis for BullMQ
  redis:
    image: redis:7-alpine
    container_name: pivot-grid-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pivot-grid-postgres
    environment:
      POSTGRES_DB: pivot_grid_dev
      POSTGRES_USER: pivot_user
      POSTGRES_PASSWORD: pivot_secure_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pivot_user -d pivot_grid_dev"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped